name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17.3
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Install bazel
      run: |
        go install github.com/bazelbuild/bazelisk@latest
        export SQUZY_VERSION=latest

    - name: Tests with cover
      run: |
        make test_cover
        bash <(curl -s https://codecov.io/bash)

    - name: Upload latest image to Docker
      if: ${{ github.ref == 'refs/heads/develop'}}
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u squzy --password-stdin
        export SQUZY_VERSION=latest
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_monitoring:squzy_push_hub_ci
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_agent_server:squzy_push_hub_ci
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_api:squzy_push_hub_ci
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_storage:squzy_push_hub_ci
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_application_monitoring:squzy_push_hub_ci
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_incident:squzy_push_hub_ci
        bazelisk run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_notification:squzy_push_hub_ci
